server:
  listen: 0.0.0.0:8080
  logTimezone: Asia/Shanghai
  logTimeFormat: '2006-01-02 15:04:05.000000'
  compressLevel: 0
s3:
  endpoint: localhost:9000
  secure: false
  accessKey: minio
  secretKey: minio123
  bucket: mybucket
  region: us-east-1
sites:
  - domains:
      - localhost:8080
    subFolder: /
    spa: false